# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['functions', 'deploy', 'cf-test-cloudbuild', '--source=.']

# options:
#   logging: CLOUD_LOGGING_ONLY

# steps:
#   # Deploy Python Cloud Function
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     args: ['gcloud', 'functions', 'deploy', 'hello-world-python',
#            '--runtime', 'python310',
#            '--trigger-http',
#            '--allow-unauthenticated',
#            '--entry-point', 'hello_world',
#            '--region', 'us-central1',
#            '--source', '.']
#     timeout: '120s'

# options:
#   logging: CLOUD_LOGGING_ONLY

# steps:
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: bash
#     args:
#       - -c
#       - |
#         pwd
#         cd gcp-cf-cloudbuild-main
#         echo "Current directory contents:"
#         ls -l
#         echo "Deploying function..."
#         gcloud functions deploy hello-world-python \
#           --runtime=python310 \
#           --trigger-http \
#           --allow-unauthenticated \
#           --entry-point=hello_world \
#           --region=us-central1 \
#           --source=.
#     timeout: '180s'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        pwd
        cd gcp-cf-cloudbuild-main
        echo "Current directory contents:"
        ls -l
        
        # Create .env file with all required environment variables
        echo "REPO_NAME=${REPO_NAME}" > .env
        echo "TEST_VAR1=${_TEST_VAR1}" >> .env
        echo "TEST_VAR2=${_TEST_VAR2}" >> .env
        echo "BUILD_ID=${BUILD_ID}" >> .env
        echo "TRIGGER_ID=${BUILD_TRIGGER_ID}" >> .env
        
        echo "Environment file contents:"
        cat .env
        
        echo "Deploying function..."
        gcloud functions deploy hello-world-python \
          --runtime=python310 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=hello_world \
          --region=us-central1 \
          --source=. \
          --set-env-vars=^:^$(cat .env | tr '\n' ',')
    timeout: '180s'
